version: '3.8'

services:
  stock-ml:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data
      # Optional: Mount configs for easy updates
      - ./conf:/app/conf:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add a scheduler service for automated pipeline runs
  stock-ml-scheduler:
    build: .
    command: ["python", "pipeline/scheduler.py"]
    volumes:
      - ./data:/app/data
      - ./conf:/app/conf:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    depends_on:
      - stock-ml